"""
This type stub file was generated by pyright.
"""

import fcntl
import v4l2
from .encoder import Encoder as Encoder, Quality as Quality
from .jpeg_encoder import JpegEncoder as JpegEncoder
from .libav_h264_encoder import LibavH264Encoder as LibavH264Encoder
from .libav_mjpeg_encoder import LibavMjpegEncoder as LibavMjpegEncoder
from .multi_encoder import MultiEncoder as MultiEncoder
from .h264_encoder import H264Encoder as H264Encoder
from .mjpeg_encoder import MJPEGEncoder as MJPEGEncoder

_hw_encoder_available = ...
if _hw_encoder_available:
    ...
else:
    ...
if _hw_encoder_available:
    ...
else:
    ...
