"""
This type stub file was generated by pyright.
"""

from picamera2.encoders.encoder import Encoder as Encoder

"""This is a base class for a multi-threaded software encoder."""
class LibavH264Encoder(Encoder):
    """Encoder class that uses libx264 for h.264 encoding."""
    def __init__(self, bitrate=..., repeat=..., iperiod=..., framerate=..., qp=..., profile=...) -> None:
        """Initialise"""
        ...
    
    @property
    def use_hw(self) -> bool:
        """Whether hardware encode will be used (can be set to True only for VC4 platforms)."""
        ...
    
    @use_hw.setter
    def use_hw(self, value) -> None:
        """Set this property in order to get libav to use the V4L2 hardware encoder (VC4 platforms only)."""
        ...
    


