"""
This type stub file was generated by pyright.
"""
from typing import Self

HDR_CTRL_ID = ...
class IMX708:
    def __init__(self, camera_num=...) -> None:
        ...
    
    def __del__(self) -> None:
        ...
    
    def close(self) -> None:
        ...
    
    def __enter__(self) -> Self:
        ...
    
    def __exit__(self, exc_type, exc_value, tb) -> None:
        ...
    
    def set_sensor_hdr_mode(self, enable: bool) -> None:
        """
        Set the sensor HDR mode (True/False) on the IMX708 device.

        Note that after changing the HDR mode, you must
        re-initialise the Picamera2 object to cache the updated sensor modes.
        """
        ...
    


