"""
This type stub file was generated by pyright.
"""

from .output import Output as Output

class PyavOutput(Output):
    """
    The PyavOutput class outputs an encoded video, and optionally audio, stream using PyAV.

    PyAv is a Python interface to libav, used by FFmpeg, and therefore can accept many different output
    types and destinations, in the same way as FFmpeg.

    The PyavOutput calls directly into libav through its Python layer, and does not pipe encoded frames
    out to a separate process like the FfmpegOutput. The PyavOutput integration means we can pass precise
    timestamps, and are not subject to the hazards of FFmpeg re-timestamping everything as it gets piped
    back in.
    """
    def __init__(self, output_name, format=..., pts=...) -> None:
        ...
    
    def start(self) -> None:
        """Start the PyavOutput."""
        ...
    
    def stop(self) -> None:
        """Stop the PyavOutput."""
        ...
    
    def outputframe(self, frame, keyframe=..., timestamp=..., packet=..., audio=...) -> None:
        """Output an encoded frame using PyAv."""
        ...
    


