"""
This type stub file was generated by pyright.
"""

from .output import Output as Output

class SplittableOutput(Output):
    """
    The SplittableOutput passes the encoded bitstream to another output (or drops them if there isn't one).

    It can be told to "split" the current output that it's been writing to, to another one. This means
    it switches seamlessly from the current output, which is closed, to a new one, without dropping
    any frames. By default, it performs the switch at a video keyframem though it can be told not to
    wait for one (by setting wait_for_keyframe to False).
    """
    def __init__(self, output=..., *args, **kwargs) -> None:
        ...
    
    def split_output(self, new_output, wait_for_keyframe=...) -> None:
        """
        Terminate the current output, switching seamlessly to the new one.

        If wait_for_keyframe is True, the switch only occurs when the next video keyframe is
        seen. Otherwise the switch happens immediately.

        THe function returns only when the switch has happened, which may entail waiting for a
        video keyframe, and the old output has been closed.
        """
        ...
    
    def outputframe(self, frame, keyframe=..., timestamp=..., packet=..., audio=...) -> None:
        ...
    
    def start(self) -> None:
        ...
    
    def stop(self) -> None:
        ...
    


