"""postprocess_yolov8_detection
This type stub file was generated by pyright.
"""

from .imx500 import IMX500 as IMX500, NetworkIntrinsics as NetworkIntrinsics
from .postprocess_efficientdet_lite0 import postprocess_efficientdet_lite0_detection as postprocess_efficientdet_lite0_detection
from .postprocess_nanodet import postprocess_nanodet_detection as postprocess_nanodet_detection
from .postprocess_yolov5 import postprocess_yolov5_detection as postprocess_yolov5_detection
from .postprocess_yolov8 import postprocess_yolov8_detection as postprocess_yolov8_detection

