"""
This type stub file was generated by pyright.
"""

import numpy as np
from typing import Tuple, Any

from numpy._typing import NDArray

"""
Efficientdet postprocessing

This code is based on:
https://github.com/google/automl/tree/master/efficientdet
"""
default_box_variance = ...
default_aspect_ratios = ...
def postprocess_efficientdet_lite0_detection(outputs: Tuple[np.ndarray, np.ndarray, np.ndarray], anchor_scale=..., min_level=..., max_level=..., box_variance=..., model_input_shape=..., min_wh=..., max_wh=..., conf_thres: float = ..., iou_thres: float = ..., max_nms_dets: int = ..., max_out_dets: int = ...) -> tuple[Any, Any, Any]:
    ...

def box_decoding_edetlite(output_annotations, H=..., W=..., anchor_scale=..., min_level=..., max_level=..., box_variance=...) -> NDArray[
    np.float64]:
    ...

def generate_anchors_EDETLITE(batch_size, featmap_sizes, H=..., W=..., anchor_scale=..., min_level=..., max_level=..., aspect_ratios=...) -> NDArray[Any]:
    """Generate configurations of anchor boxes."""
    ...

