"""
This type stub file was generated by pyright.
"""

import numpy as np
from typing import Tuple, Any

from numpy._typing import NDArray

"""
Nanodet postprocessing

This code is based on:
https://github.com/RangiLyu/nanodet
"""
def postprocess_nanodet_detection(outputs, conf: float = ..., iou_thres: float = ..., max_out_dets: int = ...) -> Tuple[np.ndarray, np.ndarray, np.ndarray]:
    ...

def generate_anchors_NANODET(featmap_sizes, strides) -> NDArray[Any]:
    ...

