"""
This type stub file was generated by pyright.
"""
from picamera2.previews.q_picamera2 import QPicamera2 as QPicamera2
from picamera2.previews.q_gl_picamera2 import QPicamera2 as QGlPicamera2

_log = ...
def __getattr__(name: str) -> type[QPicamera2] | type[QGlPicamera2]:
    ...

